---
trigger: none

stages:
  - stage: dev
    displayName: "dev"
    dependsOn: []
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: BuildTest
        displayName: "Build & Test"
        dependsOn: []
        steps:
          - task: GoTool@0
            inputs:
              version: '1.19.5'

          - bash: |
              go run main.go --task ci
            displayName: Build & Test

          - task: PublishTestResults@2
            displayName: Publish test results
            condition: always()
            inputs:
              testResultsFormat: "VSTest"
              testResultsFiles: "**/*.trx"
              mergeTestResults: true
              failTaskOnFailedTests: true

          # - task: PublishCodeCoverageResults@1
          #   displayName: Publish test coverage
          #   condition: succeeded()
          #   inputs:
          #     codeCoverageTool: "Cobertura"
          #     summaryFileLocation: $(Build.SourcesDirectory)/coverage/Cobertura.xml
          #     failIfCoverageEmpty: true
