---
version: "3.7"

services:
  seq:
    image: datalust/seq:latest
    restart: always
    ports:
      - 5341:80
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y

  jaeger:
    image: jaegertracing/all-in-one:1.22
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 14268:14268
      - 14250:14250
      - 16686:16686
      - 5778:5778

volumes:
  seq-data:
