---
version: "3.7"

services:
  seq:
    image: datalust/seq:latest
    restart: always
    command: keydb-server --requirepass tQeEsew6Svh9qh36 --appendonly yes
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y

volumes:
  seq-data:
